spring.application.name=Padel-management
# Indique à Spring d'utiliser ta base MSSQL
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=PadelDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Saeko1709

# Driver spécifique pour SQL Server
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Empêche Spring de vouloir créer les tables tout seul (on l'a fait en SQL)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true